# Generated by Django 6.1.1 on 2026-09-27 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoCatalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ação do Catálogo',
                'verbose_name_plural': 'Catálogo de Ações',
            },
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome_juridico', models.CharField(max_length=45)),
                ('nome_fantasia', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('codigo', models.CharField(primary_key=True, serialize=False)),
                ('nova_acao_texto', models.CharField(blank=True, max_length=45, null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('custo', models.FloatField()),
                ('observacao', models.CharField(blank=True, null=True)),
                ('acao_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='actions.acaocatalogo')),
                ('secretario', models.ForeignKey(db_column='Funcionario_Secretario_CPF', on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='actions.funcionario')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='actions.status')),
            ],
            options={
                'verbose_name_plural': 'Ações',
            },
        ),
        migrations.AddField(
            model_name='acaocatalogo',
            name='eixo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='actions.eixo'),
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.funcionario')),
                ('senha', models.CharField(blank=True, max_length=128)),
            ],
            bases=('actions.funcionario',),
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('preparacao', 'Em preparação'), ('execucao', 'Em execução'), ('validacao', 'Em validação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('acao', models.ForeignKey(db_column='Acao_Codigo', on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='actions.acao')),
                ('responsavel', models.ForeignKey(db_column='Funcionario_Responsavel_CPF', on_delete=django.db.models.deletion.PROTECT, related_name='etapas_responsaveis', to='actions.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_acesso', models.BooleanField(default=True)),
                ('cargo', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='actions.prefeitura')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='prefeitura',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretarios', to='actions.prefeitura'),
        ),
        migrations.CreateModel(
            name='Consultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome_juridico', models.CharField(max_length=45)),
                ('nome_fantasia', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
                ('prefeitura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultoria', to='actions.prefeitura')),
            ],
        ),
    ]
