# Generated by Django 6.1 on 2026-08-28 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('eixo', models.CharField(max_length=100)),
                ('prioridade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_preparacao', 'Em preparação'), ('em_execucao', 'Em execução'), ('em_validacao', 'Em validação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_preparacao', 'Em preparação'), ('em_execucao', 'Em execução'), ('em_validacao', 'Em validação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('prioridade', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='actions.acao')),
            ],
        ),
    ]
