# Generated by Django 6.1 on 2026-08-31 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('eixo', models.CharField(choices=[('cadastro_tributario', 'Cadastro Tributário'), ('fiscalizacao_tributaria', 'Fiscalização Tributária'), ('arrecadacao_e_cobranca', 'Arrecadação e Cobrança'), ('modernizacao_e_tecnologia', 'Modernização e Tecnologia'), ('governanca_e_legislacao', 'Governança e Legislação')], max_length=100)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_preparacao', 'Em preparação'), ('em_execucao', 'Em execução'), ('em_validacao', 'Em validação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ações',
            },
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_preparacao', 'Em preparação'), ('em_execucao', 'Em execução'), ('em_validacao', 'Em validação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='actions.acao')),
            ],
            options={
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='actions.prefeitura')),
            ],
        ),
        migrations.AddField(
            model_name='acao',
            name='prefeitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='actions.prefeitura'),
        ),
    ]
