# Generated by Django 6.1.1 on 2026-09-26 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='prefeitura',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretarios', to='actions.prefeitura'),
        ),
    ]
