# Generated by Django 6.1 on 2026-09-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('preparacao', 'Em preparação'), ('execucao', 'Em execução'), ('validacao', 'Em validação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('preparacao', 'Em preparação'), ('execucao', 'Em execução'), ('validacao', 'Em validação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20),
        ),
    ]
