# Generated by Django 6.1 on 2026-08-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name_plural': 'Ações'},
        ),
        migrations.AlterModelOptions(
            name='etapa',
            options={'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterField(
            model_name='acao',
            name='eixo',
            field=models.CharField(choices=[('cadastro_tributario', 'Cadastro Tributário'), ('fiscalizacao_tributaria', 'Fiscalização Tributária'), ('arrecadacao_e_cobranca', 'Arrecadação e Cobrança'), ('modernizacao_e_tecnologia', 'Modernização e Tecnologia'), ('governanca_e_legislacao', 'Governança e Legislação')], max_length=100),
        ),
        migrations.AlterField(
            model_name='acao',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20),
        ),
    ]
