# Generated by Django 6.1.1 on 2026-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='status',
        ),
        migrations.AlterField(
            model_name='acao',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('baixa', 'Baixa')], default='', max_length=20),
        ),
    ]
