# Generated by Django 6.1.1 on 2026-10-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultoria',
            options={'verbose_name': 'Consultoria', 'verbose_name_plural': 'Consultoria'},
        ),
        migrations.AlterModelOptions(
            name='prefeitura',
            options={'verbose_name': 'Prefeitura', 'verbose_name_plural': 'Prefeitura'},
        ),
        migrations.AddField(
            model_name='etapa',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Média', 'Media'), ('Baixa', 'Baixa')], default='', max_length=20),
        ),
    ]
