# Generated by Django 6.1 on 2026-09-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_acao_codigo_alter_acao_status_and_more'),
        ('actions', '0002_perfilusuario_primeiro_acesso_alter_acao_codigo_and_more'),
    ]

    operations = [
    ]
