# Generated by Django 6.1.1 on 2026-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_remove_etapa_status_alter_acao_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Media'), ('Baixa', 'Baixa')], default='', max_length=20),
        ),
    ]
