# Generated by Django 6.1.1 on 2026-10-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_consultoria_options_alter_prefeitura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
