# Generated by Django 6.1.1 on 2026-10-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_acao_prioridade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultoria',
            options={'verbose_name': 'Consultoria', 'verbose_name_plural': 'Consultorias'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='secretario',
            options={'verbose_name': 'Secretário', 'verbose_name_plural': 'Secretários'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.RenameField(
            model_name='acao',
            old_name='observacao',
            new_name='observacoes',
        ),
        migrations.RenameField(
            model_name='etapa',
            old_name='observacao',
            new_name='observacoes',
        ),
    ]
