# Generated by Django 6.1.1 on 2026-10-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_acao_concluida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='concluida',
        ),
        migrations.AddField(
            model_name='etapa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
