# Generated by Django 6.1 on 2026-09-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_merge_20260911_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='observacao',
            new_name='observacoes',
        ),
        migrations.RemoveField(
            model_name='acao',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='acao',
            name='acao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='nova_acao_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
