# Generated by Django 6.1.1 on 2026-10-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_remove_acao_concluida_etapa_concluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cor_nome',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
