# Generated by Django 6.1.1 on 2026-10-03 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_alter_consultoria_options_alter_funcionario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cor',
            field=models.CharField(default='#3b3b8c', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Informe uma cor hexadecimal no formato #RRGGBB.')]),
        ),
        migrations.AddField(
            model_name='status',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
