# Generated by Django 6.1 on 2026-09-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_rename_observacao_acao_observacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoCustomizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo', models.CharField(choices=[('cadastro_tributario', 'Cadastro Tributário'), ('fiscalizacao_tributaria', 'Fiscalização Tributária'), ('arrecadacao_e_cobranca', 'Arrecadação e Cobrança'), ('modernizacao_e_tecnologia', 'Modernização e Tecnologia'), ('governanca_e_legislacao', 'Governança e Legislação')], max_length=100)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ação Customizada',
                'verbose_name_plural': 'Ações Customizadas',
            },
        ),
        migrations.RemoveField(
            model_name='acao',
            name='responsavel_cpf',
        ),
    ]
