# Generated by Django 6.1 on 2026-09-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_acaocustomizada_remove_acao_responsavel_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcaoCustomizada',
        ),
    ]
