from django.db import models

class Status_eixo(models.TextChoices):
    CADASTRO_TRIBUTARIO = 'cadastro_tributario', 'Cadastro Tributário'
    FISCALIZACAO_TRIBUTARIA = 'fiscalizacao_tributaria', 'Fiscalização Tributária'
    ARRECADACAO_E_COBRANCA = 'arrecadacao_e_cobranca', 'Arrecadação e Cobrança'
    MODERNIZACAO_E_TECNOLOGIA = 'modernizacao_e_tecnologia', 'Modernização e Tecnologia'
    GOVERNANCA_E_LEGISLACAO = 'governanca_e_legislacao', 'Governança e Legislação'


class Status_status(models.TextChoices):
    PLANEJADO = 'planejado', 'Planejado'
    EM_PREPARACAO = 'preparacao', 'Em preparação'
    EM_EXECUCAO = 'execucao', 'Em execução'
    EM_VALIDACAO = 'validacao', 'Em validação'
    CONCLUIDO = 'concluido', 'Concluído'
    CANCELADO = 'cancelado', 'Cancelado'


class Status_prioridade(models.TextChoices):
    BAIXA = 'baixa', 'Baixa'
    MEDIA = 'media', 'Média'
    ALTA = 'alta', 'Alta'

class Acoes_estrategicas(models.TextChoices):
# --- EIXO 1: Cadastro Tributário ---
    DIVISOR_EIXO_1 = 'divisor_1', '--- EIXO 1: CADASTRO TRIBUTÁRIO ---'
    CAD_IMOB_1 = 'cad_imob_1', 'Atualizar cadastro imobiliário urbano (georreferenciamento e pesquisa cadastral)'
    CAD_IMOB_2 = 'cad_imob_2', 'Integrar-se com o sinter'
    CAD_IMOB_3 = 'cad_imob_3', 'Identificar imóveis não cadastrados (mesmo que individualmente)'
    CAD_IMOB_4 = 'cad_imob_4', 'Revisar áreas construídas dos imóveis (no mínimo os maiores)'
    CAD_IMOB_5 = 'cad_imob_5', 'Identificar imóveis com construção não declarada (no mínimo os maiores)'
    CAD_IMOB_6 = 'cad_imob_6', 'Identificar novos loteamentos urbanos'
    CAD_IMOB_7 = 'cad_imob_7', 'Atualizar cadastro de contribuintes do IPTU'
    CAD_IMOB_8 = 'cad_imob_8', 'Criar rotina anual de atualização cadastral'
    CAD_IMOB_9 = 'cad_imob_9', 'Integrar cadastro com dados de outras secretarias'
    CAD_IMOB_10 = 'cad_imob_10', 'Utilizar dados do cartório'
    CAD_IMOB_11 = 'cad_imob_11', 'Identificar imóveis isentos ou imunes incorretamente'
    CAD_IMOB_12 = 'cad_imob_12', 'Implantar cadastro territorial multifinalitário'
    CAD_IMOB_13 = 'cad_imob_13', 'Criar política de incentivo à atualização do cadastro'
    CAD_IMOB_14 = 'cad_imob_14', 'Fazer varredura dos imóveis com cadastro sem CPF/CNPJ do responsável'
    CAD_IMOB_15 = 'cad_imob_15', 'Conferir os imóveis com endereço incompleto ou sem numeração'
    CAD_IMOB_16 = 'cad_imob_16', 'Revisar os imóveis com isenção ativa há mais de 3 anos sem recadastramento documental'
    CAD_IMOB_17 = 'cad_imob_17', 'Implantar rotina mensal de recebimento, da Secretaria de Obras, de informações sobre alvarás, habite-se, demolições e reformas'
    CAD_IMOB_18 = 'cad_imob_18', 'Mapear loteamentos recentes ainda não refletidos integralmente no cadastro'
    CAD_MOB_1 = 'cad_mob_1', 'Atualizar cadastro de empresas'
    CAD_MOB_2 = 'cad_mob_2', 'Revisar CNAE das empresas cadastradas'
    CAD_MOB_3 = 'cad_mob_3', 'Identificar empresas ativas na Receita Federal não cadastradas'
    CAD_MOB_4 = 'cad_mob_4', 'Criar rotina de revisão de cadastro de MEI'
    CAD_MOB_5 = 'cad_mob_5', 'Rever dimensões dos imóveis (principalmente os maiores contribuintes)'
    CAD_MOB_6 = 'cad_mob_6', 'Criar cadastro separado dos 30 maiores contribuintes do ISS'
    CAD_MOB_7 = 'cad_mob_7', 'Criar cadastro separado dos 50 maiores contribuintes do TLF'
    CAD_MOB_8 = 'cad_mob_8', 'Levantar contribuintes com inscrição ativa, mas sem emissão de nota e sem recolhimento por longo período'
    CAD_MOB_9 = 'cad_mob_9', 'Revisar cadastro de contribuintes autônomos e sociedades de profissionais para verificar se mantêm os requisitos do enquadramento'

    # --- EIXO 2: Fiscalização Tributária ---
    DIVISOR_EIXO_2 = 'divisor_2', '--- EIXO 2: FISCALIZAÇÃO TRIBUTÁRIA ---'
    FISC_1 = 'fisc_1', 'Cruzar NFS-e com PGDAS'
    FISC_2 = 'fisc_2', 'Cruzar NFS-e com retenções de ISS'
    FISC_3 = 'fisc_3', 'Fiscalizar empresas de construção civil'
    FISC_4 = 'fisc_4', 'Fiscalizar serviços médicos'
    FISC_5 = 'fisc_5', 'Fiscalizar laboratórios e clínicas'
    FISC_6 = 'fisc_6', 'Fiscalizar instituições financeiras'
    FISC_7 = 'fisc_7', 'Fiscalizar cartórios'
    FISC_8 = 'fisc_8', 'Fiscalizar cooperativas de crédito'
    FISC_9 = 'fisc_9', 'Fiscalizar serviços de telecomunicações'
    FISC_10 = 'fisc_10', 'Fiscalizar empresas de energia (ex: cessão de uso de postes)'
    FISC_11 = 'fisc_11', 'Fiscalizar serviços de engenharia'
    FISC_12 = 'fisc_12', 'Fiscalizar prestadores de serviços ao município'
    FISC_13 = 'fisc_13', 'Fiscalizar o ISS retido pelo município'
    FISC_14 = 'fisc_14', 'Fiscalizar o IRRF retido pelo município'
    FISC_15 = 'fisc_15', 'Fiscalizar prestadores de serviços de tecnologia'
    FISC_16 = 'fisc_16', 'Fiscalizar empresas de transporte'
    FISC_17 = 'fisc_17', 'Fiscalizar empresas de limpeza urbana'
    FISC_18 = 'fisc_18', 'Fiscalizar academias e escolas particulares'
    FISC_19 = 'fisc_19', 'Criar monitoramento de grandes contribuintes'
    FISC_20 = 'fisc_20', 'Criar rotina de fiscalização periódica'
    FISC_21 = 'fisc_21', 'Implantar plano anual de fiscalização'
    FISC_22 = 'fisc_22', 'Criar rotina de verificação de notas canceladas e substituídas em excesso'
    FISC_23 = 'fisc_23', 'Listar contribuintes com queda brusca de emissão de NFS-e e analisar caso a caso'
    FISC_24 = 'fisc_24', 'Criar operação específica tomadores relevantes: prefeitura, câmara, fundo de saúde, fundo de assistência, grandes obras, cooperativas e bancos'
    FISC_25 = 'fisc_25', 'Criar malha básica: empresa com nota emitida e sem recolhimento, empresa com recolhimento sem nota, empresa com retenção incompatível'

    # --- EIXO 3: Arrecadação e Cobrança ---
    DIVISOR_EIXO_3 = 'divisor_3', '--- EIXO 3: ARRECADAÇÃO E COBRANÇA ---'
    ARREC_1 = 'arrec_1', 'Atualizar base da dívida ativa'
    ARREC_2 = 'arrec_2', 'Identificar maiores devedores'
    ARREC_3 = 'arrec_3', 'Implantar cobrança administrativa'
    ARREC_4 = 'arrec_4', 'Criar rotina de notificação de débitos'
    ARREC_5 = 'arrec_5', 'Revisar parcelamentos ativos'
    ARREC_6 = 'arrec_6', 'Monitorar inadimplência tributária (principalmente dos grandes contribuintes)'
    ARREC_7 = 'arrec_7', 'Implantar serviço de proteção ao crédito da dívida ativa'
    ARREC_8 = 'arrec_8', 'Implantar cobrança eletrônica'
    ARREC_9 = 'arrec_9', 'Criar política de cobrança de grandes devedores'
    ARREC_10 = 'arrec_10', 'Implantar programa de regularização fiscal'
    ARREC_11 = 'arrec_11', 'Monitorar arrecadação mensal'
    ARREC_12 = 'arrec_12', 'Revisar débitos prescritos'
    ARREC_13 = 'arrec_13', 'Priorizar execução fiscal de grandes devedores'
    ARREC_14 = 'arrec_14', 'Criar rotina de cobrança preventiva'
    ARREC_15 = 'arrec_15', 'Implantar acompanhamento de parcelamentos'
    ARREC_16 = 'arrec_16', 'Criar sistema de controle da dívida ativa'
    ARREC_17 = 'arrec_17', 'Revisar cadastro de devedores'
    ARREC_18 = 'arrec_18', 'Criar ranking de arrecadação tributária (por contribuinte)'
    ARREC_19 = 'arrec_19', 'Separar a dívida ativa em 4 grupos: até R$ 500, de R$ 500 a R$ 5 mil, de R$ 5 mil a R$ 20 mil, e acima disso'
    ARREC_20 = 'arrec_20', 'Criar lista dos 100 maiores devedores'
    ARREC_21 = 'arrec_21', 'Criar rotina mensal de envio de aviso de débito antes da inscrição ou cobrança mais dura'
    ARREC_22 = 'arrec_22', 'Relacionar débitos de empresas que contratam com o poder público'
    ARREC_23 = 'arrec_23', 'Criar rotina de cobrança preventiva para tributos de vencimento periódico'
    ARREC_24 = 'arrec_24', 'Atualizar cadastro de telefone, e-mail e endereço dos maiores devedores'

    # --- EIXO 4: Modernização e Tecnologia ---
    DIVISOR_EIXO_4 = 'divisor_4', '--- EIXO 4: MODERNIZAÇÃO E TECNOLOGIA ---'
    MOD_1 = 'mod_1', 'Implantar painel simples de acompanhamento da arrecadação mensal por tributo'
    MOD_2 = 'mod_2', 'Treinar equipe para uso da NFS-e nacional'
    MOD_3 = 'mod_3', 'Criar banco de dados fiscal'
    MOD_4 = 'mod_4', 'Implantar BI tributário'
    MOD_5 = 'mod_5', 'Criar cruzamento automatizado de dados'
    MOD_6 = 'mod_6', 'Implantar sistema de inteligência fiscal (malhas fiscais com dados da NFS-e, arrecadação e outros dados)'
    MOD_7 = 'mod_7', 'Implantar processo administrativo digital'
    MOD_8 = 'mod_8', 'Disponibilizar serviços online'
    MOD_9 = 'mod_9', 'Criar sistema de monitoramento da arrecadação'
    MOD_10 = 'mod_10', 'Integrar sistemas municipais'
    MOD_11 = 'mod_11', 'Criar dashboard de fiscalização'
    MOD_12 = 'mod_12', 'Implantar sistema de acompanhamento de metas'
    MOD_13 = 'mod_13', 'Implantar base de dados geográficos'
    MOD_14 = 'mod_14', 'Integrar base tributária com planejamento urbano'
    MOD_15 = 'mod_15', 'Implantar sistema de análise fiscal'
    MOD_16 = 'mod_16', 'Criar rotina de exportação mensal dos dados do sistema tributário para análise externa'
    MOD_17 = 'mod_17', 'Implantar sistema de comunicação virtual por WhatsApp oficial para avisos e interação com o contribuinte'

    # --- EIXO 5: Governança e Legislação ---
    DIVISOR_EIXO_5 = 'divisor_5', '--- EIXO 5: GOVERNANÇA E LEGISLAÇÃO ---'
    GOV_1 = 'gov_1', 'Revisar Código Tributário Municipal'
    GOV_2 = 'gov_2', 'Revisar procedimentos de lançamento tributário'
    GOV_3 = 'gov_3', 'Criar normas de rotina de fiscalização tributária'
    GOV_4 = 'gov_4', 'Criar normas de rotina de arrecadação tributária'
    GOV_5 = 'gov_5', 'Implantar planejamento anual da tributação'
    GOV_6 = 'gov_6', 'Criar indicadores de desempenho do setor'
    GOV_7 = 'gov_7', 'Criar rotina de reuniões de gestão tributária'
    GOV_8 = 'gov_8', 'Atualizar Planta Genérica de Valores'
    GOV_9 = 'gov_9', 'Regulamentar procedimentos tributários'
    GOV_10 = 'gov_10', 'Criar política de gestão tributária'
    GOV_11 = 'gov_11', 'Adequar legislação à reforma tributária'
    GOV_12 = 'gov_12', 'Criar programa de capacitação em legislação da equipe'
    GOV_13 = 'gov_13', 'Adequar a estrutura organizacional'
    GOV_14 = 'gov_14', 'Revisar a lei de estruturação da carreira'